import type { Prisma, RequirementType } from "@prisma/client";
import { db } from "@/server/db";
import { roundLabel } from "./round-conventions";

/**
 * Back-schedules work from hard external deadlines.
 *
 * A deadline is not a task. "Application due Nov 1" tells a student nothing
 * about what to do in September. This turns each hard deadline into dated,
 * dependency-aware work, which is the difference between a calendar and a plan.
 *
 * Lead times mirror the advice in docs/00-RESEARCH.md: recommenders are asked
 * four weeks out, essays drafted three weeks out, and submission is targeted two
 * days early because submission-night outages are well documented.
 */

type RuleKind = "prep" | "submit" | "verify";

interface Rule {
  /** Days before the hard deadline this task is due. */
  leadDays: number;
  /**
   * Drives dependencies: every "prep" task blocks "submit", which in turn blocks
   * the "verify" portal checks. Without this, the ranking happily tells a student
   * to submit an application whose essays do not exist yet.
   */
  kind: RuleKind;
  title: (context: { college: string; round: string }) => string;
  priority: number;
  estimateMinutes: number;
  /** Only emitted when the application has a requirement of this type. */
  requires?: RequirementType;
}

const RULES: Rule[] = [
  {
    leadDays: 28,
    kind: "prep",
    requires: "TEACHER_REC",
    title: ({ college }) => `Ask your teachers for recommendations for ${college}`,
    priority: 0,
    estimateMinutes: 30,
  },
  {
    leadDays: 21,
    kind: "prep",
    requires: "COUNSELOR_REC",
    title: ({ college }) => `Request counselor forms and transcript for ${college}`,
    priority: 1,
    estimateMinutes: 20,
  },
  {
    leadDays: 21,
    kind: "prep",
    requires: "ESSAY",
    title: ({ college }) => `Draft ${college} supplemental essays`,
    priority: 1,
    estimateMinutes: 180,
  },
  {
    leadDays: 14,
    kind: "prep",
    requires: "TEST_SCORES",
    title: ({ college }) => `Send test scores to ${college}`,
    priority: 2,
    estimateMinutes: 15,
  },
  {
    leadDays: 14,
    kind: "prep",
    requires: "CSS_PROFILE",
    title: ({ college }) => `Complete the CSS Profile for ${college}`,
    priority: 1,
    estimateMinutes: 90,
  },
  {
    leadDays: 7,
    kind: "prep",
    requires: "ESSAY",
    title: ({ college }) => `Finalize ${college} essays`,
    priority: 1,
    estimateMinutes: 90,
  },
  {
    // Never the deadline itself. Portals fall over on submission night.
    leadDays: 2,
    kind: "submit",
    title: ({ college, round }) => `Review and submit ${college} (${round})`,
    priority: 0,
    estimateMinutes: 60,
  },
  {
    leadDays: -7,
    kind: "verify",
    title: ({ college }) => `Check the ${college} portal — confirm everything arrived`,
    priority: 1,
    estimateMinutes: 10,
  },
  {
    leadDays: -14,
    kind: "verify",
    title: ({ college }) => `Second portal check for ${college}`,
    priority: 2,
    estimateMinutes: 10,
  },
];

const DAY = 86_400_000;

export async function backScheduleApplication(
  userId: string,
  applicationId: string,
): Promise<number> {
  const application = await db.application.findFirstOrThrow({
    where: { id: applicationId, userId },
    include: {
      college: { select: { name: true } },
      requirements: { select: { type: true } },
      deadlines: { where: { kind: "APPLICATION" }, orderBy: { dueAt: "asc" }, take: 1 },
    },
  });

  const deadline = application.deadlines[0];
  if (!deadline) return 0;

  const present = new Set(application.requirements.map((r) => r.type));
  const context = {
    college: application.college.name,
    round: roundLabel(application.round),
  };

  const rows: Prisma.TaskCreateManyInput[] = [];
  const kindByKey = new Map<string, RuleKind>();

  for (const [index, rule] of RULES.entries()) {
    if (rule.requires && !present.has(rule.requires)) continue;

    const generatorKey = `app:${applicationId}:rule:${index}`;
    kindByKey.set(generatorKey, rule.kind);

    rows.push({
      userId,
      applicationId,
      title: rule.title(context),
      status: "TODO",
      priority: rule.priority,
      dueAt: new Date(deadline.dueAt.getTime() - rule.leadDays * DAY),
      estimateMinutes: rule.estimateMinutes,
      labels: ["auto"],
      isAutoGenerated: true,
      // Idempotent: regenerating updates in place instead of duplicating.
      generatorKey,
      sortOrder: index,
    });
  }

  // Only auto-generated, still-open tasks are replaced. Anything the student
  // completed or edited survives regeneration.
  await db.task.deleteMany({
    where: {
      userId,
      applicationId,
      isAutoGenerated: true,
      status: { in: ["TODO", "BLOCKED"] },
    },
  });
  await db.task.createMany({ data: rows, skipDuplicates: true });

  await linkDependencies(userId, applicationId, kindByKey);

  return rows.length;
}

/**
 * Prep work blocks submission; submission blocks portal verification. Blocked
 * tasks are hidden from the ranked queue, so the app never suggests submitting
 * an application whose essays are not written.
 */
async function linkDependencies(
  userId: string,
  applicationId: string,
  kindByKey: Map<string, RuleKind>,
) {
  const tasks = await db.task.findMany({
    where: { userId, applicationId, isAutoGenerated: true },
    select: { id: true, generatorKey: true },
  });

  const byKind = { prep: [] as string[], submit: [] as string[], verify: [] as string[] };
  for (const task of tasks) {
    const kind = task.generatorKey ? kindByKey.get(task.generatorKey) : undefined;
    if (kind) byKind[kind].push(task.id);
  }

  const edges: { blockingTaskId: string; blockedTaskId: string }[] = [];
  for (const submitId of byKind.submit) {
    for (const prepId of byKind.prep) {
      edges.push({ blockingTaskId: prepId, blockedTaskId: submitId });
    }
    for (const verifyId of byKind.verify) {
      edges.push({ blockingTaskId: submitId, blockedTaskId: verifyId });
    }
  }

  if (edges.length > 0) {
    await db.taskDependency.createMany({ data: edges, skipDuplicates: true });
  }
}

export async function backScheduleAll(userId: string): Promise<number> {
  const applications = await db.application.findMany({
    where: { userId, archivedAt: null },
    select: { id: true },
  });

  let total = 0;
  for (const application of applications) {
    total += await backScheduleApplication(userId, application.id);
  }
  return total;
}
